// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import FlashController from "./flash_controller"
application.register("flash", FlashController)

import MissionRequestModeController from "./mission_request_mode_controller"
application.register("mission-request-mode", MissionRequestModeController)
