class ReimbursementsController < ApplicationController
  before_action :set_reimbursement, only: %i[show edit update destroy confirm_destroy]

  def index
    @reimbursements = policy_scope(Reimbursement).ordered
  end

  def show
  end

  def new
    @reimbursement = current_user.reimbursements.build(request_date: Date.current)
    authorize @reimbursement
  end

  def create
    @reimbursement = current_user.reimbursements.build(reimbursement_params)
    @reimbursement.name = ReimbursementCodeGenerator.call(user: current_user)
    @reimbursement.reimbursement_date ||= ReimbursementDateGenerator.call(departure_date: @reimbursement.departure_date)
    @reimbursement.total_amount = ReimbursementTotalCalculator.call(reimbursement: @reimbursement)
    authorize @reimbursement

    if @reimbursement.save
      redirect_to reimbursements_path, notice: "Rimborso spese creato con successo."
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    @reimbursement.assign_attributes(reimbursement_params)
    @reimbursement.reimbursement_date ||= ReimbursementDateGenerator.call(departure_date: @reimbursement.departure_date)
    @reimbursement.total_amount = ReimbursementTotalCalculator.call(reimbursement: @reimbursement)

    if @reimbursement.save
      redirect_to reimbursements_path, notice: "Rimborso spese aggiornato con successo."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def confirm_destroy
  end

  def print
    authorize Reimbursement, :print?
    @q = current_user.reimbursements.ransack(search_params)
    @reimbursements = @q.result(distinct: true)
      .includes(:user, :transport, :vehicle, :reason, :place, :structure, :path)
      .order(id: :desc)

    respond_to do |format|
      format.html
      format.pdf { send_reimbursements_pdf }
    end
  end

  def destroy
    @reimbursement.destroy
    redirect_to reimbursements_path, notice: "Rimborso spese eliminato con successo.", status: :see_other
  end

  private

  # Ransack refuses unpermitted parameters, so the print form's two date bounds
  # are the only search keys that ever reach it.
  def search_params
    return {} unless params[:q].is_a?(ActionController::Parameters)

    params[:q].permit(:departure_date_gteq, :departure_date_lteq)
  end

  def send_reimbursements_pdf
    if @reimbursements.empty?
      redirect_to print_reimbursements_path(q: search_params), alert: "Nessun rimborso spese da stampare per il periodo selezionato."
    else
      send_data ReimbursementsPdf.new(@reimbursements).render,
        filename: "rimborsi-spese.pdf", type: "application/pdf", disposition: "inline"
    end
  end

  def set_reimbursement
    @reimbursement = policy_scope(Reimbursement).find(params[:id])
    authorize @reimbursement
  end

  FULL_PERMITTED_FIELDS = %i[
    departure_date return_date request_date reimbursement_date
    reason_id place_id structure_id path_id
    reason_fr place_fr structure_fr path_fr
    path_lenght_fr highway_cost_fr
    transport_id vehicle_id
    parking_cost food_cost room_cost ticket_cost generic_cost
  ].freeze

  # A reimbursement auto-generated by the mission-request approval workflow only
  # accepts edits to the five expense fields; every other key is dropped here, so
  # a hand-crafted request (dev tools, console, curl) cannot change the rest.
  def reimbursement_params
    permitted = if @reimbursement&.from_mission_request?
      Reimbursement::MISSION_REQUEST_EDITABLE_FIELDS
    else
      FULL_PERMITTED_FIELDS
    end

    params.require(:reimbursement).permit(*permitted)
  end
end
