class Reimbursement < ApplicationRecord
  belongs_to :user
  belongs_to :reason, optional: true
  belongs_to :place, optional: true
  belongs_to :structure, optional: true
  belongs_to :path, optional: true
  belongs_to :transport
  belongs_to :vehicle, optional: true
  belongs_to :mission_request, optional: true

  # Expense fields a user completes on a reimbursement that was auto-generated by
  # the mission-request approval workflow.
  MISSION_REQUEST_EDITABLE_COST_FIELDS = %w[
    parking_cost food_cost room_cost ticket_cost generic_cost
  ].freeze

  # Every field a user may still edit on an auto-generated reimbursement. The
  # reimbursement date plus the expense fields; everything else is copied from
  # the approved request and stays read-only.
  MISSION_REQUEST_EDITABLE_FIELDS = (%w[reimbursement_date] + MISSION_REQUEST_EDITABLE_COST_FIELDS).freeze

  validates :name, presence: true, uniqueness: true
  validates :mission_request_id, uniqueness: true, allow_nil: true
  validates :departure_date, presence: true
  validates :return_date, presence: true
  validates :request_date, presence: true
  validates :reimbursement_date, presence: true
  validate :stored_or_free_fields_present

  scope :ordered, -> { order(request_date: :desc) }

  # Ransack only ever needs the departure date: the print form filters on it and
  # nothing else is exposed to user-supplied search params.
  def self.ransackable_attributes(_auth_object = nil)
    %w[departure_date]
  end

  def self.ransackable_associations(_auth_object = nil)
    []
  end

  def display_reason
    reason&.name || reason_fr
  end

  def display_place
    place&.name || place_fr
  end

  def display_structure
    structure&.name || structure_fr
  end

  def display_path
    path&.name || path_fr
  end

  def display_path_lenght
    path&.lenght || path_lenght_fr
  end

  def display_highway_cost
    path&.highway_cost || highway_cost_fr
  end

  def from_mission_request?
    mission_request_id.present?
  end

  private

  def stored_or_free_fields_present
    return if stored_fields_present? || free_fields_present?

    errors.add(:base, "Compilare tutti i campi in modalità \"Modelli Memorizzati\" oppure tutti i campi in modalità \"Campi Liberi\"")
  end

  def stored_fields_present?
    reason.present? && place.present? && structure.present? && path.present?
  end

  def free_fields_present?
    reason_fr.present? && place_fr.present? && structure_fr.present? && path_fr.present?
  end
end
